services:
  - type: web
    name: news-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn news:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SERPER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false 